### ISSUE TITLE
Websocket subscribe mined block event

### ISSUE THREAD

**Issue by z1617** [aeternity/epoch#1645]
## Actual Behavior

I use the following golang code to receive the mined block event from epoch, but it doesn't work:

```
package main

import (
        "flag"
        "log"
        "net/url"
        "os"
        "os/signal"
        "time"

        "github.com/gorilla/websocket"
)

var addr = flag.String("addr", "127.0.0.1:3114", "epoch websocket address")

func loop() {
        u := url.URL{Scheme: "ws", Host: *addr, Path: "/websocket"}
        log.Printf("connecting to %s", u.String())

        c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
        if err != nil {
                log.Fatal("dial:", err)
        }
        defer c.Close()

        log.Println("connected")

        c.WriteMessage(websocket.TextMessage, []byte("{\"payload\":{\"type\":\"mined_block\"},\"target\":\"chain\",\"action\":\"subscribe\"}"))

        for {
                c.SetReadDeadline(time.Now().Add(time.Duration(30) * time.Minute))
                _, message, err := c.ReadMessage()
                if err != nil {
                        log.Println("read:", err)
                        return
                }
                log.Printf("recv: %s", message)
        }
}

func main() {
        flag.Parse()
        log.SetFlags(0)

        interrupt := make(chan os.Signal, 1)
        signal.Notify(interrupt, os.Interrupt)

        go func() {
                <-interrupt
                os.Exit(1)
        }()

        for {
                loop()
        }
}
```

After started, the client receives:

```
{"action":"subscribe","origin":"chain","payload":{"result":"ok","subscribed_to":{"type":"mined_block"}},"tag":"untagged"}
```

But after awhile the epoch server close the connection, and the client got:

```
read: websocket: close 1000 (normal)
```

No mined block event is received.

## Steps to Reproduce the Problem

```
go get github.com/gorilla/websocket
go build ae_ws.go
./ae_ws
```
  

## Logs, error output, etc.

The `epoch.log` shows:

```
2018-10-13 09:20:45.888 [debug] <0.1245.0>@aec_block_generator:handle_info:99 ignored event top_changed
```
 
My epoch.yml is:

```
---
sync:
    port: 3115
    external_port: 3015

keys:
    dir: keys
    password: ""

http:
    external:
        port: 3013
    internal:
        port: 3113

websocket:
    internal:
        port: 3114
    channel:
        port: 3014

mining:
    beneficiary: "ak_2E21GCWxEQqEB58ComXS66oiNdqPvgXxbFkfs93dUmM7Vfickp"
    autostart: true

chain:
    persist: true
    db_path: ./my_db
```

## Specifications

  - OS: ubuntu
  - Node Version: 0.24.0
