### ISSUE TITLE
docker image rc6 gets connection handshake failures to seed nodes

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#1855]
## Expected Behavior
Node should sync up normally

## Actual Behavior
Handshake errors, kid is not cool enough to salute us

## Steps to Reproduce the Problem
myepoch.yaml
```
sync:
    port: 3015
    external_port: 3015
    listen_address: 0.0.0.0

keys:
    dir: ./keys/
    peer_password: "password"

http:
    external:
        port: 3013
        listen_address: 0.0.0.0
    internal:
        port: 3113
        listen_address: 0.0.0.0

websocket:
    channel:
        port: 3014
        listen_address: 0.0.0.0

mining:
    beneficiary: "ak_depositkey"
    autostart: true
    cuckoo:
        miner:
           edge_bits: 29
           executable: lean29-avx2
           extra_args: ""

logging:
    level: "info"

chain:
    persist: true
    db_path: /home/epoch/node/data/
```

mkdir -p /opt/epoch/{db,keys}
chwon 1000:1000 /opt/epoch{db,keys,myepoch.yaml}
docker run -d --cpus=1 --name epoch -p 3013:3013 -p 3014:3014 -p 3015:3015 -p 127.0.0.1:3113:3113 -v /opt/epoch/myepoch.yaml:/home/epoch/node/epoch.yaml -v /opt/epoch/db:/home/epoch/node/data/mnesia -v /opt/epoch/keys:/home/epoch/node/keys aeternity/epoch:v1.0.0-rc6  
  
## Logs, error output, etc.
http://18.195.109.60:3013/v2/status
```
{
	"difficulty": 17412781914,
	"genesis_key_block_hash": "kh_umdcbdLjN1Aerm3tpp1q3QR3TjrmTDXiKF8abEgWsoSCu9jHm",
	"listening": true,
	"node_revision": "4fd0f23d52bc4663545d124b17e97366f6c234b9",
	"node_version": "1.0.0-rc6",
	"peer_count": 103,
	"pending_transactions_count": 0,
	"protocols": [
		{
			"effective_at_height": 0,
			"version": 1
		}
	],
	"solutions": 0,
	"syncing": true
}
```

My status
```
{
	"difficulty": 16777216,
	"genesis_key_block_hash": "kh_umdcbdLjN1Aerm3tpp1q3QR3TjrmTDXiKF8abEgWsoSCu9jHm",
	"listening": true,
	"node_revision": "4fd0f23d52bc4663545d124b17e97366f6c234b9",
	"node_version": "1.0.0-rc6",
	"peer_count": 4,
	"pending_transactions_count": 0,
	"protocols": [
		{
			"effective_at_height": 0,
			"version": 1
		}
	],
	"solutions": 0,
	"syncing": true
}
```

Error
```
09:03:57.598 [info] Connection handshake failed - timeout was from <<"18.195.109.60">>
09:03:57.622 [info] Connection handshake failed - timeout was from <<"18.130.148.7">>
09:03:57.773 [info] Connection handshake failed - timeout was from <<"52.10.46.160">>
09:03:57.783 [info] Connection handshake failed - timeout was from <<"13.250.162.250">>
```

## Specifications
Docker: aeternity/epoch:v1.0.0-rc6 image
